#!/usr/bin/perl

$pi = 4 * atan2(1, 1);

@ang = (0, $pi * 1/4, $pi * 2/4, $pi * 3/4, $pi * 4/4, $pi * 5/4, $pi * 6/4, $pi * 7/4);

$sc = .5;

while (<>) {
	($x, $y, $Y, $d[0], $d[1], $d[2], $d[3], $d[4], $d[5], $d[6], $d[7]) = split(/ /);

	for ($i = 0; $i < 8; $i++) {
		$d1 = $d[$i];
		$d2 = $d[($i + 1) % 8];

		$a1 = $ang[$i];
		$a2 = $ang[($i + 1) % 8];

		if ($d1 ne "x" && $d2 ne "x") {
			$x1 = 612 * ($x + $d1 * cos($a1) * $sc);
			$y1 = 612 * ($y + $d1 * sin($a1) * $sc);

			$x2 = 612 * ($x + $d2 * cos($a2) * $sc);
			$y2 = 612 * ($y + $d2 * sin($a2) * $sc);

			print "$x1 $y1 moveto $x2 $y2 lineto stroke\n";
		}
	}
}
