#!/usr/bin/perl

$pi = 4 * atan2(1, 1);

@ang = (0, $pi * 1/3, $pi * 2/3, $pi * 3/3, $pi * 4/3, $pi * 5/3);

$sc = .3;

while (<>) {
	($l, $a, $b, $d[0], $d[1], $d[2], $d[3], $d[4], $d[5]) = split(/ /);

	for ($i = 0; $i < 6; $i++) {
		$d1 = $d[$i];
		$d2 = $d[($i + 1) % 6];

		$a1 = $ang[$i];
		$a2 = $ang[($i + 1) % 6];

		if ($d1 ne "x" && $d2 ne "x") {
			$x1 = 306 * ($a + $d1 * cos($a1) * $sc) / 100 + 306;
			$y1 = 306 * ($b + $d1 * sin($a1) * $sc) / 100 + 306;

			$x2 = 306 * ($a + $d2 * cos($a2) * $sc) / 100 + 306;
			$y2 = 306 * ($b + $d2 * sin($a2) * $sc) / 100 + 306;

			print "$x1 $y1 moveto $x2 $y2 lineto stroke\n";
		}
	}
}
