#!/usr/bin/perl

while (<>) {
	next if /#/;

	($x, $y) = split(/ /);

	$wn = ($x - 142) / (1125 - 142) * (15 - 25) + 25;
	$wl = 1 / $wn * 10000;
	$l10 = ($y - 136) / (526 - 136) * (1 - 2) + 2;
	$l = $l10 * log(10);
        $v = exp($l) / 100;

	print "$wl $v\n";
}
