#!/usr/bin/perl

while (<>) {
	if (/^#/ || /^\s+$/) {
		print;
	} elsif (/^scale ([0-9-.]+) ([0-9-.]+) = ([0-9-.]+) ([0-9-.]+), ([0-9-.]+) ([0-9-.]+) = ([0-9-.]+) ([0-9-.]+)/) {
		$x1 = $1;
		$y1 = $2;
		$outx1 = $3;
		$outy1 = $4;
		$x2 = $5;
		$y2 = $6;
		$outx2 = $7;
		$outy2 = $8;
		$logscale = 0;
	} elsif (/^scale ([0-9-.]+) ([0-9-.]+) = ([0-9-.]+) log ([0-9-.]+), ([0-9-.]+) ([0-9-.]+) = ([0-9-.]+) log ([0-9-.]+)/) {
		$x1 = $1;
		$y1 = $2;
		$outx1 = $3;
		$outy1 = log($4);
		$x2 = $5;
		$y2 = $6;
		$outx2 = $7;
		$outy2 = log($8);
		$logscale = 1;
	} elsif (/^([0-9-.]+) ([0-9-.]+)/) {
		$x = ($1 - $x1) / ($x2 - $x1) * ($outx2 - $outx1) + $outx1;
		$y = ($2 - $y1) / ($y2 - $y1) * ($outy2 - $outy1) + $outy1;

		if ($logscale) {
			$y = exp($y);
		}

		print "$x $y\n";
	} else {
		print STDERR "???? $_";
	}
}
